heat_template_version: '2015-04-30'

description: Deploy one instance

parameters:
  key_name:
    type: string
  network_name:
    type: string

resources:

  web_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 80
          port_range_max: 80
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 443
          port_range_max: 443
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 22 
          port_range_max: 22
  
  instance_1:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: ubuntu-22.04
      flavor: m1.small
      networks:
      - port: { get_resource: server_1_port }
  
  server_1_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network_name }
      security_groups:
        - default
        - { get_resource: web_secgroup }
